// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace RestApiTesting.Framework.Jaguar.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "Sprint4")]
    [Xunit.TraitAttribute("Category", "PostsSteps")]
    public partial class DeletePostsFeature : Xunit.IClassFixture<DeletePostsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "DeletePosts.feature"
#line hidden
        
        public DeletePostsFeature(DeletePostsFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "DeletePosts", "As a non-authenticated user,\r\nI want the ability to delete a post.", ProgrammingLanguage.CSharp, new string[] {
                        "Sprint4",
                        "PostsSteps"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="A non-authenticated user successfully deletes a post")]
        [Xunit.TraitAttribute("FeatureTitle", "DeletePosts")]
        [Xunit.TraitAttribute("Description", "A non-authenticated user successfully deletes a post")]
        [Xunit.TraitAttribute("Category", "AcceptanceCriteria")]
        public virtual void ANon_AuthenticatedUserSuccessfullyDeletesAPost()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A non-authenticated user successfully deletes a post", null, new string[] {
                        "AcceptanceCriteria"});
#line 8
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
     testRunner.When("a non-authenticated user sends a request to delete a post", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
     testRunner.Then("the service\'s response is \"OK\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 11
   testRunner.And("the service returns the empty post", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="A non-authenticated user attempts to delete a post with nonexistent id")]
        [Xunit.TraitAttribute("FeatureTitle", "DeletePosts")]
        [Xunit.TraitAttribute("Description", "A non-authenticated user attempts to delete a post with nonexistent id")]
        [Xunit.TraitAttribute("Category", "NegativePath")]
        public virtual void ANon_AuthenticatedUserAttemptsToDeleteAPostWithNonexistentId()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A non-authenticated user attempts to delete a post with nonexistent id", null, new string[] {
                        "NegativePath"});
#line 14
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 15
     testRunner.When("a non-authenticated user sends a request to delete a nonexistent post", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
     testRunner.Then("the service\'s response is \"OK\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 17
   testRunner.And("the service returns the empty post", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                DeletePostsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                DeletePostsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
